apiVersion: v2
appVersion: 3.7.0
name: kafka
version: 0.0.1
dependencies:
- name: kafka
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 29.3.10
- condition: zookeeper.enabled
  name: zookeeper
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 13.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
    - bitnami-common
  version: 2.x.x
