apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-broker-0
  labels:
    app: kafka-broker-0
spec:
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/kafka/controller-0"
  capacity:
    storage: 8Gi
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: data-kafka-broker-0
    namespace: stock-price-tracker

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-broker-1
  labels:
    app: kafka-broker-1
spec:
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/kafka/controller-1"
  capacity:
    storage: 8Gi
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: data-kafka-broker-1
    namespace: stock-price-tracker

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/zookeeper"
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 8Gi
  claimRef:
    name: data-kafka-zookeeper-0
    namespace: stock-price-tracker

