kafka:
  broker:
    automountServiceAccountToken: true
    replicaCount: 2
  controller:
    replicaCount: 0
    resourcesPreset: large
  externalAccess:
    autoDiscovery:
      enabled: true
      image:
        tag: 1.30.3-debian-12-r0
    enabled: true
  extraConfig: |
    max.message.bytes = 1048576
    offsets.topic.replication.factor = 1
    default.replication.factor = 1
    delete.topic.enable = true
    auto.create.topics.enable = false

  image:
    tag: 3.7.1-debian-12-r2
  kraft:
    enabled: false
  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    external:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
  metrics:
    jmx:
      image:
        tag: 1.0.1-debian-12-r2
  rbac:
    create: true
  volumePermissions:
    enabled: true
    image:
      tag: 12-debian-12-r25
  zookeeper:
    enabled: true

