apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    chart: kafka
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 30.1.2
    helm:
      releaseName: kafka
  destination:
    server: "https://kubernetes.default.svc"
    namespace: stock-tracker